

cultureSites = {
   "type":"FeatureCollection",
   "features":[
      {
         "type":"Feature",
         "properties":{
            "name":"Caral",
            "group_id":"0",
            "site_name":"Caral",
            "type":"Archeological Site",
            "longitude":"-77.523208",
            "latitude":"-10.892386",
            "province":"Lima",
            "color":"#51517A",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -77.523208,
               -10.892386
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Lima",
            "group_id":"6",
            "site_name":"Huaca Pucllana",
            "alt_name":" ",
            "type":"Archeological Site",
            "longitude":"-77.033539",
            "latitude":"-12.110026",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_Cao_Viejo",
            "photo":"images/badurria.jpg",
            "color":"#949494",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -77.033539,
               -12.110026
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Lima",
            "group_id":"6",
            "site_name":"Pachacamac",
            "type":"Archeological Site",
            "longitude":"-76.899525",
            "latitude":"-12.259386",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_Cao_Viejo",
            "photo":"images/el_paraiso.jpg",
            "color":"#949494",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -76.899525,
               -12.259386
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Chavin",
            "group_id":"1",
            "site_name":"Chavin de Huantar",
            "type":"Archeological Site",
            "longitude":"-77.177324",
            "latitude":"-9.592795",
            "color":"#998B30",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -77.177324,
               -9.592795
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Chavin",
            "group_id":"1",
            "site_name":"Huaca Prieta",
            "type":"Archeological Site",
            "longitude":"-79.306949",
            "latitude":"-7.924008",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_Prieta",
            "photo":"images/huaca_prieta.jpg",
            "color":"#998B30",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -79.306949,
               -7.924008
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Chavin",
            "group_id":"1",
            "site_name":"Kotosh",
            "type":"Archeological Site",
            "longitude":"-76.279443",
            "latitude":"-9.930747",
            "wiki_link":"https://es.wikipedia.org/wiki/Kotosh",
            "photo":"images/kotosh.jpg",
            "color":"#998B30",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -76.279443,
               -9.930747
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Chavin",
            "group_id":"1",
            "site_name":"Las Aldas",
            "type":"Archeological Site",
            "longitude":"-78.296674",
            "latitude":"-9.701645",
            "wiki_link":"https://es.wikipedia.org/wiki/Las_Haldas",
            "photo":"images/aldas.png",
            "color":"#998B30",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -78.296674,
               -9.701645
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Chavin",
            "group_id":"1",
            "site_name":"Bandurria",
            "type":"Archeological Site",
            "longitude":"-77.587886",
            "latitude":"-11.186705",
            "wiki_link":"https://es.wikipedia.org/wiki/Bandurria_(sitio_arqueol%C3%B3gico)",
            "photo":"images/badurria.jpg",
            "color":"#998B30",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -77.587886,
               -11.186705
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Chavin",
            "group_id":"1",
            "site_name":"El Paraiso",
            "type":"Archeological Site",
            "longitude":"-77.118409",
            "latitude":"-11.953733",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_El_Para%C3%ADso",
            "photo":"images/el_paraiso.jpg",
            "color":"#998B30",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -77.118409,
               -11.953733
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Paracas",
            "group_id":"2",
            "site_name":"Cerro Colorado",
            "type":"Archeological Site",
            "longitude":"-75.23",
            "latitude":"-14.033",
            "province":"Ica",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_El_Para%C3%ADso",
            "photo":"images/huaca_prieta.jpg",
            "color":"#8C4B4B",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -75.23,
               -14.033
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Paracas",
            "group_id":"2",
            "site_name":"Paracas Necropolis",
            "type":"Archeological Site",
            "comments":"Approximate location",
            "longitude":"-76.279413",
            "latitude":"-13.85452",
            "color":"#8C4B4B",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -76.279413,
               -13.85452
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Paracas",
            "group_id":"2",
            "site_name":"Alto del Molino",
            "type":"Archeological Site",
            "comments":"Approximate location",
            "longitude":"-76.200752",
            "latitude":"-13.689871",
            "color":"#8C4B4B",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -76.200752,
               -13.689871
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Paracas",
            "group_id":"2",
            "site_name":"Puerto Nuevo",
            "type":"Archeological Site",
            "comments":"Approximate location",
            "longitude":"-76.228773",
            "latitude":"-13.759007",
            "color":"#8C4B4B",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -76.228773,
               -13.759007
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Paracas",
            "group_id":"2",
            "site_name":"Karwa",
            "alt_name":"Carhua",
            "type":"Archeological Site",
            "comments":"Approximate location",
            "longitude":"-76.151978",
            "latitude":"-14.202881",
            "color":"#8C4B4B",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -76.151978,
               -14.202881
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Paracas",
            "group_id":"2",
            "site_name":"Chongos",
            "type":"Archeological Site",
            "comments":"Approximate location",
            "longitude":"-76.131019",
            "latitude":"-13.70033",
            "color":"#8C4B4B",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -76.131019,
               -13.70033
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Nazca",
            "group_id":"3",
            "site_name":"Cahuachi",
            "type":"Archeological Site",
            "longitude":"-75.116667",
            "latitude":"-14.818611",
            "province":"Ica",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_El_Para%C3%ADso",
            "photo":"images/huaca_prieta.jpg",
            "color":"#51517A",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -75.116667,
               -14.818611
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Nazca",
            "group_id":"3",
            "site_name":"Pernil Alto",
            "type":"Archeological Site",
            "longitude":"-75.206",
            "latitude":"-14.485",
            "province":"Ica",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_El_Para%C3%ADso",
            "photo":"images/kotosh.jpg",
            "color":"#51517A",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -75.206,
               -14.485
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Nazca",
            "group_id":"3",
            "site_name":"Los Molinos",
            "alt_name":"Molino",
            "type":"Archeological Site",
            "longitude":"-74.953",
            "latitude":"-14.412",
            "province":"Ica",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_El_Para%C3%ADso",
            "photo":"images/aldas.png",
            "color":"#51517A",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -74.953,
               -14.412
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Nazca",
            "group_id":"3",
            "site_name":"La Muña",
            "alt_name":"Cerro Muña",
            "type":"Archeological Site",
            "longitude":"-75.213",
            "latitude":"-14.548",
            "province":"Ica",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_El_Para%C3%ADso",
            "photo":"images/badurria.jpg",
            "color":"#51517A",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -75.213,
               -14.548
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Nazca",
            "group_id":"3",
            "site_name":"Lineas de Nasca",
            "type":"Archeological Site",
            "longitude":"-75.134767",
            "latitude":"-14.705824",
            "province":"Ica",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_El_Para%C3%ADso",
            "photo":"images/el_paraiso.jpg",
            "color":"#51517A",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -75.134767,
               -14.705824
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Nazca",
            "group_id":"3",
            "site_name":"Ocucaje",
            "alt_name":"Geoglifos Ocucaje",
            "type":"Archeological Site",
            "longitude":"-75.642",
            "latitude":"-14.413",
            "province":"Ica",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_El_Para%C3%ADso",
            "photo":"images/huaca_prieta.jpg",
            "color":"#51517A",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -75.642,
               -14.413
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Recuay",
            "group_id":"4",
            "site_name":"Huilcahuaín",
            "alt_name":"Wilkawain",
            "type":"Archeological Site",
            "longitude":"-77.511507",
            "latitude":"-9.483099",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_Cao_Viejo",
            "photo":"images/aldas.png",
            "color":"#8A6148",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -77.511507,
               -9.483099
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Recuay",
            "group_id":"4",
            "site_name":"Yayno",
            "type":"Archeological Site",
            "longitude":"-77.4557",
            "latitude":"-8.885541",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_Cao_Viejo",
            "photo":"images/badurria.jpg",
            "color":"#8A6148",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -77.4557,
               -8.885541
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Recuay",
            "group_id":"4",
            "site_name":"Tinyash",
            "type":"Archeological Site",
            "longitude":"-77.000163",
            "latitude":"-8.945565",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_Cao_Viejo",
            "photo":"images/el_paraiso.jpg",
            "color":"#8A6148",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -77.000163,
               -8.945565
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Mochica",
            "group_id":"5",
            "site_name":"Huaca Cao Viejo",
            "type":"Archeological Site",
            "longitude":"-79.303447",
            "latitude":"-7.915156",
            "province":"La Libertad",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_Cao_Viejo",
            "photo":"images/kotosh.jpg",
            "color":"#6078C0",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -79.303447,
               -7.915156
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Mochica",
            "group_id":"5",
            "site_name":"Sipán",
            "type":"Archeological Site",
            "longitude":"-79.600219",
            "latitude":"-6.798751",
            "province":"La Libertad",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_Cao_Viejo",
            "photo":"images/aldas.png",
            "color":"#6078C0",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -79.600219,
               -6.798751
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Mochica",
            "group_id":"5",
            "site_name":"Pampa Grande",
            "type":"Archeological Site",
            "longitude":"-79.474219",
            "latitude":"-6.762238",
            "province":"La Libertad",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_Cao_Viejo",
            "photo":"images/badurria.jpg",
            "color":"#6078C0",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -79.474219,
               -6.762238
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Mochica",
            "group_id":"5",
            "site_name":"San José de Moro",
            "type":"Archeological Site",
            "longitude":"-79.438684",
            "latitude":"-7.181054",
            "province":"La Libertad",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_Cao_Viejo",
            "photo":"images/el_paraiso.jpg",
            "color":"#6078C0",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -79.438684,
               -7.181054
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Mochica",
            "group_id":"5",
            "site_name":"Pacatnamú",
            "type":"Archeological Site",
            "longitude":"-79.584324",
            "latitude":"-7.317887",
            "province":"La Libertad",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_Cao_Viejo",
            "photo":"images/huaca_prieta.jpg",
            "color":"#6078C0",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -79.584324,
               -7.317887
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Mochica",
            "group_id":"5",
            "site_name":"Huaca el brujo",
            "type":"Archeological Site",
            "longitude":"-79.304007",
            "latitude":"-7.911842",
            "province":"La Libertad",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_Cao_Viejo",
            "photo":"images/kotosh.jpg",
            "color":"#6078C0",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -79.304007,
               -7.911842
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Mochica",
            "group_id":"5",
            "site_name":"Pirámides de Moche",
            "type":"Archeological Site",
            "longitude":"-78.998264",
            "latitude":"-8.141529",
            "province":"La Libertad",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_Cao_Viejo",
            "photo":"images/aldas.png",
            "color":"#6078C0",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -78.998264,
               -8.141529
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Cajamarca",
            "group_id":"7",
            "site_name":"Collor",
            "type":"Archeological Site",
            "longitude":"-78.329757",
            "latitude":"-7.232845",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_Cao_Viejo",
            "photo":"images/kotosh.jpg",
            "color":"#5F8242",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -78.329757,
               -7.232845
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Cajamarca",
            "group_id":"7",
            "site_name":"Ventanillas de Otuzco",
            "type":"Archeological Site",
            "longitude":"-78.457626",
            "latitude":"-7.125648",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_Cao_Viejo",
            "photo":"images/aldas.png",
            "color":"#5F8242",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -78.457626,
               -7.125648
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Tiahuanaco",
            "group_id":"8",
            "site_name":"Tiahuanaco",
            "alt_name":"Tiwanaku",
            "type":"Archeological Site",
            "longitude":"-68.673909",
            "latitude":"-16.55535",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_Cao_Viejo",
            "photo":"images/kotosh.jpg",
            "color":"#5D5D5D",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -68.673909,
               -16.55535
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Chachapoyas",
            "group_id":"9",
            "site_name":"Karajía",
            "type":"Archeological Site",
            "longitude":"-78.021397",
            "latitude":"-6.162543",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_El_Para%C3%ADso",
            "photo":"images/huaca_prieta.jpg",
            "color":"#18684C",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -78.021397,
               -6.162543
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Chachapoyas",
            "group_id":"9",
            "site_name":"Vilaya",
            "alt_name":"Gran Vilaya",
            "type":"Archeological Site",
            "longitude":"-78.094378",
            "latitude":"-6.293966",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_Cao_Viejo",
            "photo":"images/kotosh.jpg",
            "color":"#18684C",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -78.094378,
               -6.293966
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Chachapoyas",
            "group_id":"9",
            "site_name":"Kuélap",
            "type":"Archeological Site",
            "longitude":"-77.923866",
            "latitude":"-6.416864",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_Cao_Viejo",
            "photo":"images/aldas.png",
            "color":"#18684C",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -77.923866,
               -6.416864
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Chachapoyas",
            "group_id":"9",
            "site_name":"Revash",
            "type":"Archeological Site",
            "longitude":"-77.856202",
            "latitude":"-6.540595",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_Cao_Viejo",
            "photo":"images/badurria.jpg",
            "color":"#18684C",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -77.856202,
               -6.540595
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Chachapoyas",
            "group_id":"9",
            "site_name":"Macro",
            "type":"Archeological Site",
            "longitude":"-77.917158",
            "latitude":"-6.365329",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_Cao_Viejo",
            "photo":"images/el_paraiso.jpg",
            "color":"#18684C",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -77.917158,
               -6.365329
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Chachapoyas",
            "group_id":"9",
            "site_name":"Gran Pajatén",
            "type":"Archeological Site",
            "longitude":"-77.418637",
            "latitude":"-7.648195",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_Cao_Viejo",
            "photo":"images/huaca_prieta.jpg",
            "color":"#18684C",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -77.418637,
               -7.648195
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Chachapoyas",
            "group_id":"9",
            "site_name":"Llactacocha",
            "alt_name":"Laguna de los Condores",
            "type":"Archeological Site",
            "longitude":"-77.698025",
            "latitude":"-6.847821",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_Cao_Viejo",
            "photo":"images/kotosh.jpg",
            "color":"#18684C",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -77.698025,
               -6.847821
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Lambayeque",
            "group_id":"11",
            "site_name":"Batán Grande",
            "type":"Archeological Site",
            "longitude":"-79.795927",
            "latitude":"-6.469807",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_Cao_Viejo",
            "photo":"images/badurria.jpg",
            "color":"#2D837F",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -79.795927,
               -6.469807
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Lambayeque",
            "group_id":"11",
            "site_name":"Complejo Sicán",
            "type":"Archeological Site",
            "longitude":"-79.790298",
            "latitude":"-6.472203",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_Cao_Viejo",
            "photo":"images/el_paraiso.jpg",
            "color":"#2D837F",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -79.790298,
               -6.472203
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Lambayeque",
            "group_id":"11",
            "site_name":"Complejo El Brujo",
            "type":"Archeological Site",
            "longitude":"-79.303782",
            "latitude":"-7.914043",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_Cao_Viejo",
            "photo":"images/badurria.jpg",
            "color":"#2D837F",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -79.303782,
               -7.914043
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Chimu",
            "group_id":"12",
            "site_name":"Chan Chan",
            "type":"Archeological Site",
            "longitude":"-79.074581",
            "latitude":"-8.105191",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_Cao_Viejo",
            "photo":"images/huaca_prieta.jpg",
            "color":"#AD7F93",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -79.074581,
               -8.105191
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Chimu",
            "group_id":"12",
            "site_name":"Túcume",
            "type":"Archeological Site",
            "longitude":"-79.842931",
            "latitude":"-6.5163",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_Cao_Viejo",
            "photo":"images/kotosh.jpg",
            "color":"#AD7F93",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -79.842931,
               -6.5163
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "name":"Chimu",
            "group_id":"12",
            "site_name":"Paramonga",
            "type":"Archeological Site",
            "longitude":"-77.841389",
            "latitude":"-10.653038",
            "wiki_link":"https://es.wikipedia.org/wiki/Huaca_Cao_Viejo",
            "photo":"images/aldas.png",
            "color":"#AD7F93",
            "radius":"5"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -77.841389,
               -10.653038
            ]
         }
      }
   ]
}